# --- Required options --- #
title: CS-401/spaghetti solution
author: spaghetti solution

# --- Navigation bar --- #
navbar-links:
  Resources:
    - Dataset: "http://www.cs.cmu.edu/~ark/personas/"
    - Repository: "https://github.com/NValsa/NValsa.github.io"

# --- Logo --- #
avatar: "/assets/img/spaghettisolution.png"
round-avatar: true

# --- General options --- #
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
navbar-var-length: false

# --- Colours --- #
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# --- Misc --- #
date_format: "%B %-d, %Y"

# --- Jekyll defaults --- #
timezone: "Europe/Zurich"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  -
    scope:
      path: ""
    values:
      layout: "page"

# --- Exclude from production site --- #
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
